// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using PlantProjectDomain.Repository;
using System;

namespace PlantProjectDomain.Migrations
{
    [DbContext(typeof(RepositoryContext))]
    [Migration("20171209080322_Genus")]
    partial class Genus
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.1-rtm-125")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("PlantProjectDomain.Domain.Conservation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("Conservations");
                });

            modelBuilder.Entity("PlantProjectDomain.Domain.Family", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("Familys");
                });

            modelBuilder.Entity("PlantProjectDomain.Domain.Genus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("name");

                    b.HasKey("Id");

                    b.ToTable("Genus");
                });

            modelBuilder.Entity("PlantProjectDomain.Domain.Plant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("ConservationId");

                    b.Property<int?>("FamilyId");

                    b.Property<int?>("GenusId");

                    b.Property<string>("LatinName");

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.HasIndex("ConservationId");

                    b.HasIndex("FamilyId");

                    b.HasIndex("GenusId");

                    b.ToTable("Plants");
                });

            modelBuilder.Entity("PlantProjectDomain.Domain.Plant", b =>
                {
                    b.HasOne("PlantProjectDomain.Domain.Conservation", "Conservation")
                        .WithMany()
                        .HasForeignKey("ConservationId");

                    b.HasOne("PlantProjectDomain.Domain.Family", "Family")
                        .WithMany()
                        .HasForeignKey("FamilyId");

                    b.HasOne("PlantProjectDomain.Domain.Genus", "Genus")
                        .WithMany()
                        .HasForeignKey("GenusId");
                });
#pragma warning restore 612, 618
        }
    }
}
